version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    rebase-strategy: disabled
    versioning-strategy: increase
    schedule:
      interval: daily
